# Generated by Django 4.1.2 on 2022-10-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='about',
            field=models.TextField(default='none', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.TextField(default='https://images.freeimages.com/images/previews/266/gift-1422193.jpg', max_length=500),
            preserve_default=False,
        ),
    ]
