# Generated by Django 4.1.2 on 2022-10-10 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_board_about_board_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift_Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.CharField(max_length=255)),
                ('image', models.TextField(max_length=500)),
                ('link', models.TextField(max_length=255)),
                ('date_needed', models.DateField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_ideas', to='main_app.board')),
            ],
        ),
    ]
